### ISSUE TITLE
 咨询报错

### ISSUE THREAD

**Issue by tytyty123** [dubbo/jmeter-plugins-dubbo#45]
感觉像是序列话问题，请大神帮忙看看。

jmeter报错日志

2018-12-18 17:18:31,010 WARN c.a.d.r.e.c.ExchangeCodec:  [DUBBO] Skip input stream 1, dubbo version: 1.3.7-jar-with-dependencies, current host: 192.168.0.1
2018-12-18 17:18:31,010 WARN c.a.d.r.e.c.ExchangeCodec:  [DUBBO] Skip input stream 1, dubbo version: 1.3.7-jar-with-dependencies, current host: 192.168.0.1
2018-12-18 17:18:31,010 WARN c.a.d.r.e.c.ExchangeCodec:  [DUBBO] Skip input stream 1, dubbo version: 1.3.7-jar-with-dependencies, current host: 192.168.0.1
2018-12-18 17:18:31,010 WARN c.a.d.r.p.d.DubboCodec:  [DUBBO] Decode request failed: com/esotericsoftware/kryo/KryoException, dubbo version: 1.3.7-jar-with-dependencies, current host: 192.168.0.1
java.lang.NoClassDefFoundError: com/esotericsoftware/kryo/KryoException
	at com.alibaba.dubbo.common.serialize.kryo.KryoSerialization.deserialize(KryoSerialization.java:51) ~[jmeter-plugins-dubbo-1.3.7-jar-with-dependencies.jar:?]
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboCodec.deserialize(DubboCodec.java:154) ~[jmeter-plugins-dubbo-1.3.7-jar-with-dependencies.jar:?]
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboCodec.decodeBody(DubboCodec.java:123) [jmeter-plugins-dubbo-1.3.7-jar-with-dependencies.jar:?]
	at com.alibaba.dubbo.remoting.exchange.codec.ExchangeCodec.decode(ExchangeCodec.java:125) [jmeter-plugins-dubbo-1.3.7-jar-with-dependencies.jar:?]
	at com.alibaba.dubbo.remoting.exchange.codec.ExchangeCodec.decode(ExchangeCodec.java:85) [jmeter-plugins-dubbo-1.3.7-jar-with-dependencies.jar:?]
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboCountCodec.decode(DubboCountCodec.java:46) [jmeter-plugins-dubbo-1.3.7-jar-with-dependencies.jar:?]
	at com.alibaba.dubbo.remoting.transport.netty.NettyCodecAdapter$InternalDecoder.messageReceived(NettyCodecAdapter.java:133) [jmeter-plugins-dubbo-1.3.7-jar-with-dependencies.jar:?]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:80) [jmeter-plugins-dubbo-1.3.7-jar-with-dependencies.jar:?]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [jmeter-plugins-dubbo-1.3.7-jar-with-dependencies.jar:?]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) [jmeter-plugins-dubbo-1.3.7-jar-with-dependencies.jar:?]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:274) [jmeter-plugins-dubbo-1.3.7-jar-with-dependencies.jar:?]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:261) [jmeter-plugins-dubbo-1.3.7-jar-with-dependencies.jar:?]
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:349) [jmeter-plugins-dubbo-1.3.7-jar-with-dependencies.jar:?]
	at org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys(NioWorker.java:280) [jmeter-plugins-dubbo-1.3.7-jar-with-dependencies.jar:?]
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:200) [jmeter-plugins-dubbo-1.3.7-jar-with-dependencies.jar:?]
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [jmeter-plugins-dubbo-1.3.7-jar-with-dependencies.jar:?]
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:44) [jmeter-plugins-dubbo-1.3.7-jar-with-dependencies.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_121]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.ClassNotFoundException: com.esotericsoftware.kryo.KryoException
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	... 20 more
2018-12-18 17:18:31,010 WARN c.a.d.r.e.c.ExchangeCodec:  [DUBBO] Skip input stream 1, dubbo version: 1.3.7-jar-with-dependencies, current host: 192.168.0.1

**Comment by ningyu1** [comment]
将这个类com.esotericsoftware.kryo.KryoException所在的jar包放入JMETER_HOME/lib/ext下试试

**Comment by tytyty123** [comment]
多谢大神，补充包，后面就没这问题了
