### ISSUE TITLE
git clone下来后打包，扔到jmeter3.0启动报错

### ISSUE THREAD

**Issue by zheteng123** [dubbo/jmeter-plugins-dubbo#8]
mac系统，idea，jdk1.8，jmeter3.0
打包jmeter-plugins-dubbo-1.3.3-jar-with-dependencies.jar后，扔到jmeter3.0的lib/ext下，不能启动jmeter，报如下错误：
 FATAL - jmeter.JMeter: An error occurred:  java.lang.IncompatibleClassChangeError: class org.springframework.core.type.classre
ading.AbstractRecursiveAnnotationVisitor has interface org.springframework.asm.AnnotationVisitor as super class
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.apache.jorphan.reflect.ClassFinder.isChildOf(ClassFinder.java:377)
        at org.apache.jorphan.reflect.ClassFinder.access$000(ClassFinder.java:47)
        at org.apache.jorphan.reflect.ClassFinder$ExtendsClassFilter.accept(ClassFinder.java:92)
        at org.apache.jorphan.reflect.ClassFinder.findClassesInOnePath(ClassFinder.java:441)
        at org.apache.jorphan.reflect.ClassFinder.findClasses(ClassFinder.java:289)
        at org.apache.jorphan.reflect.ClassFinder.findClassesThatExtend(ClassFinder.java:264)
        at org.apache.jmeter.gui.action.ActionRouter.populateCommandMap(ActionRouter.java:310)

**Comment by zheteng123** [comment]
jmeter 3.2能正常启动，但运行时获取结果为null,具体如下：
{"detailMessage":null,"stackTrace":[{"declaringClass":"io.github.ningyu.jmeter.plugin.dubbo.sample.DubboSample","methodName":"callDubbo","fileName":"DubboSample.java","lineNumber":434},{"declaringClass":"io.github.ningyu.jmeter.plugin.dubbo.sample.DubboSample","methodName":"sample","fileName":"DubboSample.java","lineNumber":324},{"declaringClass":"org.apache.jmeter.threads.JMeterThread","methodName":"executeSamplePackage","fileName":"JMeterThread.java","lineNumber":491},{"declaringClass":"org.apache.jmeter.threads.JMeterThread","methodName":"processSampler","fileName":"JMeterThread.java","lineNumber":425},{"declaringClass":"org.apache.jmeter.threads.JMeterThread","methodName":"run","fileName":"JMeterThread.java","lineNumber":254},{"declaringClass":"java.lang.Thread","methodName":"run","fileName":"Thread.java","lineNumber":745}],"suppressedExceptions":[]}

**Comment by zheteng123** [comment]
是不是因为被测接口接收的参数只是一个string，不是key value这种

**Comment by ningyu1** [comment]
@zheteng123 第一个问题：1.3.3版本放入jmeter3.0下报错，这个错误是jar包冲突错误，检查你jmeter的lib下jar包：spring-asm，可能存在jar包冲突，打出来的插件依赖的jar都包含进去了，因此不要单独的再去添加依赖包，冲突的类：org.springframework.asm.AnnotationVisitor

**Comment by ningyu1** [comment]
@zheteng123 第二个问题：提供一下jmeter的查看结果树中的请求栏目参数截图，然后再看是什么问题，参数不管是什么类型只要可以json序列化与反序列化就可以支持

**Comment by ningyu1** [comment]
@zheteng123 插件在使用的时候最好是使用干净的jmeter，如果lib下有其他测试的jar包最好是清楚，避免jar包冲突

**Comment by zheteng123** [comment]
![image](https://user-images.githubusercontent.com/14845275/40885360-572f8604-6757-11e8-9202-6062b4288b1f.png)
![image](https://user-images.githubusercontent.com/14845275/40885354-3db0c134-6757-11e8-8cc6-178fa2d00600.png)
![image](https://user-images.githubusercontent.com/14845275/40885364-762ce2f4-6757-11e8-9ab0-7110fa31bbd9.png)
![image](https://user-images.githubusercontent.com/14845275/40885366-7ba8608c-6757-11e8-994f-ac3846a562fe.png)
被测接口就是接收一个string的参数
![image](https://user-images.githubusercontent.com/14845275/40885375-925333e8-6757-11e8-8253-f4c48a1dee46.png)

**Comment by zheteng123** [comment]
PS：原来您也喜欢死神啊  头像赞~

**Comment by ningyu1** [comment]
@zheteng123 你描述的这个问题是因为，你的服务端暴漏接口的时候没有选择version，但是jmeter 插件在访问的时候version默认填写的是1.0.0，因此报错其实你可以去看服务端的日志有详细的错误信息，删掉version的输入信息即可，例如下图:

![image](https://user-images.githubusercontent.com/3387548/40902679-65c6b88a-6807-11e8-8f7d-17b9019f00a3.png)

**Comment by ningyu1** [comment]
@zheteng123 在查看结果树中可以看到信息如下：

![image](https://user-images.githubusercontent.com/3387548/40902742-a721cc3e-6807-11e8-89e9-99ddc3c5b224.png)
![image](https://user-images.githubusercontent.com/3387548/40902734-a0b00884-6807-11e8-8630-c7d901185ee3.png)
![image](https://user-images.githubusercontent.com/3387548/40902711-8b80ea3c-6807-11e8-9dba-9e37cda463ad.png)

**Comment by zheteng123** [comment]
请问这个版本是什么的版本号？

**Comment by zheteng123** [comment]
搞定了 ，sayHello测试接口version为空成功，其他接口version写1.0.0也成功了 多谢这么及时解答！ @ningyu1
